package com.crawl.vue;

import java.awt.event.ActionEvent;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

import com.crawl.downloader.Noeud;
import com.crawl.manager.Manager;
import com.crawl.observer.Observer;

/*
 * Web Crawler GUI Frame
 * Created on 7 janv. 2013, 16:53:37
 */

/**
 * Main frame class for the web crawler application
 * Implements Observer pattern to receive updates from the Manager
 * 
 * * Copyright (c) 2013 Khaled Kadri
 * Licensed under MIT License
 * https://github.com/khaledkadri
 */

public class Fenetre extends javax.swing.JFrame implements Observer{

    /** Manager instance to handle crawling operations */
	public Manager manager;
	
	/** List to store URLs for aspiration/crawling */
	ArrayList<URL> _aspiration;
	
    /** Creates new form Crawler2 */
    public Fenetre() {
    	super("Crawler");
        initComponents();
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        
        // Initialize main panel for search criteria
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        
        // Text field for keyword to search
        _motcle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        
        // Dropdown for language selection
        _langue = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        
        // Dropdown for depth level (1 to 100)
        profondeur = new javax.swing.JComboBox();
        for(int i = 1 ; i <= 100 ;i++)
        profondeur.addItem(i);
        
        jLabel8 = new javax.swing.JLabel();
        
        // Text field for download location
        emplacement = new javax.swing.JTextField();
        
        // Button to start search
        rechercher = new javax.swing.JButton();
        
        // Button to stop search
        stop = new javax.swing.JButton();
        
        // Vertical separator
        jSeparator1 = new javax.swing.JSeparator();
        
        Aspiration = new javax.swing.JLabel();
        
        // Label to display current aspiration
        _Aspiration = new javax.swing.JLabel();
        
        // Progress bar to show search progress
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar1.setMinimum(0);
        jProgressBar1.setStringPainted(true);
        
        jLabel7 = new javax.swing.JLabel();
        
        // Scroll pane for results table
        jScrollPane1 = new javax.swing.JScrollPane();
        
        // Table to display search results
        jTable2 = new javax.swing.JTable();
        jTable2 = new javax.swing.JTable(new DefaultTableModel(new Object[][]{},
                new String[]{"Title"}));
        
        // Scroll pane for seed URLs table
        jScrollPane2 = new javax.swing.JScrollPane();
        
        // Table to display starting seed URLs
        jTable1 = new javax.swing.JTable(new DefaultTableModel(new Object[][]{},
                new String[]{"URL"}));
        
        Aspiration1 = new javax.swing.JLabel();
        
        // Label to display current depth level
        _profondeur = new javax.swing.JLabel();
        
        // Set default location to user downloads folder
        emplacement.setText(System.getProperty("user.dir") +
                System.getProperty("file.separator")+"downloads\\");
        
        // Initialize stop button
        stop = new javax.swing.JButton();
        stop.setEnabled(false);
                
        // Set default close operation
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // Create and configure search criteria panel with border
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Search criteria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        // Label for search keyword
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel1.setText("Search string:");

        // Configure keyword text field
        _motcle.setFont(new java.awt.Font("Tahoma", 0, 14));

        // Label for language selection
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel3.setText("Language:");

        // Configure language dropdown with list of supported languages
        _langue.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afrikaans", "Arabic", "Armenian", "Belarusian", "Bulgarian", "Catalan", "Chinese", "Chinese", "Croatian", "Czech", "Danish", "Dutch", "English", "Esperanto", "Estonian", "Filipino", "Finnish", "French", "German", "Greek", "Hebrew", "Hindi", "Hungarian", "Icelandic", "Indonesian", "Italian", "Japanese", "Korean", "Latvian", "Lithuanian", "Norwegian", "Persian", "Polish", "Portuguese", "Romanian", "Russian", "Serbian", "Slovak", "Slovenian", "Spanish", "Swahili", "Swedish", "Thai", "Turkish", "Ukrainian", "Vietnamese" }));
        _langue.setSelectedItem("English");

        // Label for depth level
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel5.setText("Depth:");

        // Configure panel layout
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel2))
                            .addComponent(_langue, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_motcle, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profondeur, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(_motcle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_langue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(profondeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(40, 40, 40))
        );

        // Label for download location
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel8.setText("Location:");

        // Add action listener to location field
        emplacement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emplacementActionPerformed(evt);
            }
        });

        // Configure search button
        rechercher.setFont(new java.awt.Font("Arial", 1, 14));
        rechercher.setText("Search");
        rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });

        // Configure stop button
        stop.setFont(new java.awt.Font("Arial", 1, 14));
        stop.setText("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        
        // Configure vertical separator appearance
        jSeparator1.setForeground(new java.awt.Color(153, 153, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        // Label for aspiration display
        Aspiration.setFont(new java.awt.Font("Times New Roman", 1, 14));
        Aspiration.setText("Current URL:");

        // Label for progression display
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel7.setText("Progression:");

        // Configure results table scroll pane with border
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)), "Results"));

        // Initialize results table
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable2);

        // Configure seed URLs table scroll pane with border
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)), "Starting point"));

        // Initialize seed URLs table
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        // Label for depth level display
        Aspiration1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        Aspiration1.setText("Depth:");

        // Configure main frame layout
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(73, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(emplacement, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(rechercher)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(stop)))
                            .addGap(29, 29, 29)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(Aspiration)
                            .addComponent(Aspiration1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_profondeur, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_Aspiration, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(_Aspiration, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                            .addComponent(Aspiration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_profondeur, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                            .addComponent(Aspiration1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emplacement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rechercher)
                            .addComponent(stop))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)))
                .addContainerGap())
        );

        // Pack the frame to fit all components
        pack();
    }// </editor-fold>

    /**
     * Handle location field action
     */
    private void emplacementActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * Handle search button action
     */
    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	// Create and start a new thread to perform the search asynchronously
    	thread = new Thread(new Runnable() {
    	    public void run() {
    	    	// Initialize and clear the tables
    	        initjtable();
    	        // Initialize the manager model
    	        initModel();
    	        
    	        // Check if a keyword has been entered
    	        if(!_motcle.getText().isEmpty()){
    	        	// Disable search and enable stop button
    	            rechercher.setEnabled(false);
    	            stop.setEnabled(true);
    	            
    	            // Reset progress bar
    	            jProgressBar1.setValue(0);
    	            
    	            // Configure manager with search parameters
    	            manager.setMot(_motcle.getText());
    	            manager.setLangue(_langue.getSelectedItem().toString());
    	            manager.init();
    	            manager.setEmplacement(emplacement.getText());
    	            emplacement.setText(emplacement.getText()+_motcle.getText());
    	            manager.setProfondeur(profondeur.getSelectedIndex()+1);
    	            
    	            // Launch the search
    	            manager.lancerrecherche();
    	            
    	            // Get total number of URLs to process
    	            taille = manager.getURLs().size();
    	            jProgressBar1.setMaximum(taille);
    	            
    	            // Start crawling through the queue
    	            manager.parcourirLaQueue();
    	        }
    	        else{
    	        	// Reset location if no keyword entered
    	            emplacement.setText(System.getProperty("user.dir") +
    	                    System.getProperty("file.separator")+"downloads\\");
    	        }
    	    }

    	    /**
    	     * Initialize tables for search results and seed URLs
    	     */
    	    private void initjtable() {
    	        // Create empty table model for seed URLs with URL column
    	        jTable1.setModel(new DefaultTableModel(new Object[][]{},
    	                        new String[]{"URL"}) {
    	            public boolean isCellEditable(int row, int column) {
    	                // Make cells read-only
    	                return false;
    	            }
    	        });
    	        
    	        // Create empty table model for results with URL and Title columns
    	        jTable2.setModel(new DefaultTableModel(new Object[][]{},
    	                        new String[]{"URL","Title","Status"}) {
    	            public boolean isCellEditable(int row, int column) {
    	                // Make cells read-only
    	                return false;
    	            }
    	        });
    	    }
    	});
    	// Start the search thread
    	thread.start();
    }                                          

    /**
     * Handle stop button action
     */
    private void stopActionPerformed(ActionEvent evt) {
        // Stop the search thread
        thread.stop();
        
        // Reset location to default
        emplacement.setText(System.getProperty("user.dir") +
                System.getProperty("file.separator")+"downloads\\");
        
        // Disable stop button and enable search button
        stop.setEnabled(false);
        rechercher.setEnabled(true);
    }
    
    /**
     * Initialize the Manager model and add this frame as observer
     */
    private void initModel(){
        this.manager = new Manager();
        this.manager.addObserver(this);
    }

    /**
     * Update method to refresh the seed URLs table
     */
    @Override
    public void update(Object[] _aspiration) {
        // Get the model from the seed URLs table
        DefaultTableModel model =
                (DefaultTableModel) jTable1.getModel();
        
        // Add each aspiration/seed URL to the table
        for(int i = 0 ; i < _aspiration.length ; i++)
            model.addRow(new Object[]{_aspiration[i]});
    }

    /**
     * Update method to refresh the results table
     */
    @Override
    public void updateresultat(String url, String titre, int status) {
        // Calculate new row count for progress
        int size = jTable2.getModel().getRowCount() + 1;
        DefaultTableModel model =
                (DefaultTableModel) jTable2.getModel();
        
        // Add found URL and title to results table
        model.addRow(new Object[]{url, titre, status});
        
        // Update progress bar with new value
        jProgressBar1.setValue(size);
        
        // Check if search is complete
        if(jProgressBar1.getValue() == taille){
            // Reset location to default
            emplacement.setText(System.getProperty("user.dir") +
                    System.getProperty("file.separator")+"downloads\\");
            
            // Enable search button and disable stop button
            rechercher.setEnabled(true);
            stop.setEnabled(false);
        }
    }

    /**
     * Update method to display current URL being processed
     */
    @Override
    public void updateurl(URL url) {
        // Display the current URL being crawled
        _Aspiration.setText(url.toString());
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel Aspiration;
    private javax.swing.JLabel Aspiration1;
    private javax.swing.JLabel _Aspiration;
    private javax.swing.JComboBox _langue;
    private javax.swing.JTextField _motcle;
    private javax.swing.JLabel _profondeur;
    private javax.swing.JTextField emplacement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox profondeur;
    private javax.swing.JButton rechercher;
    private javax.swing.JButton stop;
    private Thread thread;
    private int taille;
    
    // End of variables declaration
    
    /**
     * Update method to set the maximum value for progress bar
     */
    @Override
    public void updatepb(int taille) {
        // Set the progress bar maximum to total URL count
        jProgressBar1.setMaximum(taille);
        // Store the total size for later comparison
        this.taille = taille;
    }

    /**
     * Update method to refresh the progress bar with processed URLs count
     */
    @Override
    public void updateurlTraites(int urlTraites) {
        // Update progress bar value with number of processed URLs
        jProgressBar1.setValue(urlTraites);
        
        // Check if all URLs have been processed
        if(jProgressBar1.getValue() == taille){
            // Reset location to default
            emplacement.setText(System.getProperty("user.dir") +
                    System.getProperty("file.separator")+"downloads\\");
            
            // Enable search button and disable stop button
            rechercher.setEnabled(true);
            stop.setEnabled(false);
        }
    }

    /**
     * Receive node information (not implemented)
     */
    @Override
    public void recevoirUrl(Noeud noeud) {
        // TODO Auto-generated method stub
    }

    /**
     * Remove URL node (not implemented)
     */
    @Override
    public void supprimeUrl(Noeud noeud) {
        // TODO Auto-generated method stub
    }
    
    // End of variables declaration

    /**
     * Update method to display remaining depth level
     */
    @Override
    public void updateprfondeur(int profondeur) {
        // Calculate remaining depth by subtracting current depth from selected depth
        int pro = this.profondeur.getSelectedIndex() + 1 - profondeur + 1;
        // Display the remaining depth
        this._profondeur.setText(String.valueOf(pro));
    }
}